routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!*/



Route::get('/royalorchard', 'WebController@index');
Route::POST('/userData/getUserData','UserDataController@getUserData');
Route::POST('/slider/getSliderData','SliderController@getSliderData');
Route::resource('userData','UserDataController');
Route::get('userData/edit/{id}', 'UserDataController@edit');
///Route::post('userData/update', 'UserDataController@update');



//Route::resource('userData','UserDataController');


Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::get('projects/search','ProjectController@search');
Route::resource('projects', 'ProjectController');
Route::get('project_location/search','ProjectLocationController@search');
Route::resource('project_location','ProjectLocationController');
Route::resource('master_plan','MasterPlanController');
Route::get('news/search','NewsController@search');
Route::resource('news','NewsController');
Route::get('newsletters/search','NewsletterController@search');
Route::resource('newsletters','NewsletterController');
Route::resource('slider','SliderController');
Route::get('gallery/search','GalleryController@search');
Route::resource('gallery','GalleryController');
Route::resource('kfcategory','KfcategoryController');
Route::get('kfeature/search','KfeatureController@search');
Route::resource('kfeature','KfeatureController');
Route::resource('kfgallery','KfgalleryController');
Route::resource('sfeature','SfeatureController');
Route::resource('homes_category','HomesCategoryController');
Route::resource('villas','VillasController');
Route::get('payment_plan/search','PaymentPlanController@search');
Route::resource('payment_plan','PaymentPlanController');
Route::get('development_progress/search','DevelopmentProgressController@search');
Route::resource('development_categories','DevelopmentCategoryController');
Route::resource('development_progress','DevelopmentProgressController');
Route::resource('royal_medicare','RoyalMedicareController');
Route::resource('salescenter','SalescenterController');
Route::resource('size','SizeController');
Route::get('file/search','FileController@search');
Route::resource('file','FileController');
Route::resource('associates','AssociatesController');

Route::get('web/mission','WebController@mission');
Route::get('web/objective','WebController@objective');
Route::get('web/brouchers','WebController@brouchers');
Route::get('web/newsletters','WebController@newsletters');
Route::get('web/news','WebController@news');
Route::get('web/news_detail/{id}','WebController@news_detail');
Route::get('web/contactus','WebController@contactus');
Route::get('web/multan','WebController@multan');
Route::get('web/sargodha','WebController@sargodha');
Route::get('web/sahiwal','WebController@sahiwal');
Route::resource('web','WebController');
Route::resource('setting','SettingController');
Route::post('sendmail', 'EmailController@index');

/*Route::get('/', function () {
return view('web.index');
});*/
Auth::routes();
Route::get('/home', 'WebController@home')->name('home');
Route::get('/royalorchard', 'WebController@index');
/*Route::get('/royalorchard', function () {
    return view('web.index');
})->name('royalorchard');*/
///Route::get('/royalorchard', 'WebController@index')->name('royalorchard');

app/Broucher.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Broucher extends Model
{
    //
}

app/Http/Controllers/BroucherController.php
<?php

namespace App\Http\Controllers;

use App\Broucher;
use Illuminate\Http\Request;

class BroucherController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       if(Auth::Check()){
$brouchers=brouchers::all();
$projects=Project::all();
return view('newsletters.index',compact('brouchers','projects'));
}else{
Auth::logout();
return redirect('/login');
}
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Broucher  $broucher
     * @return \Illuminate\Http\Response
     */
    public function show(Broucher $broucher)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Broucher  $broucher
     * @return \Illuminate\Http\Response
     */
    public function edit(Broucher $broucher)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Broucher  $broucher
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Broucher $broucher)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Broucher  $broucher
     * @return \Illuminate\Http\Response
     */
    public function destroy(Broucher $broucher)
    {
        //
    }
}

resources/views/brouchers/create.blade.php
@extends('layouts.app')
@section('title','Create Newsletter')
@section('content')
<div class="row-fluid">
	@if(count($errors)>0)
	<ul>
		
		<div class="note note-success"> @foreach($errors->all() as $error)
			<strong style="color: red"> {{  $error }}</strong><br>
			@endforeach
		</div>
		
	</ul>
	@endif
	<div class="span12">
		
		<div class="widget-box">
			<div class="widget-header">
				<h4>Create Newsletters</h4>
				<span class="widget-toolbar">
				</span>	</div>
				<div class="widget-body"><div class="widget-body-inner">
					<div class="widget-main">
						<form   action="{{url('/newsletters')}}" method="post" enctype="multipart/form-data" accept-charset="utf-8">
							<div class="row-fluid">
								  <input type="hidden" name="noimg" value="No-Image" placeholder="">
								<input type="hidden" name="_token" value="{{csrf_token()}}">
								<label for="form-field-8">Title</label>
								<input name="title" value="{{old('title')}}" class="span6 limited" type="text" id="form-field-4" placeholder="Enter Title">
							</div>
							<hr>
							<div class="row-fluid">
								<label for="form-field-9">Project Name</label>
								<select  name="project_id" class="span6" id="form-field-select-1">
									
									<option selected value="">Select Project</option>
									@foreach($projects as $project)
									<option value="{{$project->id}}">{{$project->project_name}}</option>
									@endforeach
								</select>
							</div>
							
							<div class="row-fluid">
								  <input type="hidden" name="noimg" value="No-Image" placeholder="">
								
								<label for="form-field-8">Link</label>
								<input name="link" value="{{old('link')}}" class="span6 limited" type="text" id="form-field-4" placeholder="Enter Title">
							</div>
							<div class="row-fluid">
								<label for="form-field-9">Status</label>
								<select  name="status" class="span6" id="form-field-select-1">
									
									<option selected value="">Select Status</option>
									
									<option value="1">Enabled</option>
									<option value="0">Disabled</option>
								
								</select>
							</div>
									<hr>
							<div class="row-fluid">	
								<label for="form-field-8">Pdf File</label>
								 <input type="file" name="image" value="" placeholder="Select Pdf File" >
							</div><hr>
							<div class="row-fluid">	
								<label for="form-field-8">Thumbnail Image</label>
								 <input type="file" name="thumbnail" value="" placeholder="Select Images for Thumbnail" multiple>
							</div>
							<div class="form-actions">
								<button class="btn btn-info" type="submit"><i class="icon-ok"></i> Submit</button>
								&nbsp; &nbsp; &nbsp;
								<button class="btn" type="reset"><i class="icon-undo"></i> Reset</button>
							</div> </form>
						</div>
					</div></div>
				</div>
			</div>
			
		</div>
		@endsection

resources/views/brouchers/edit.blade.php
@extends('layouts.app')
@section('title','Edit News')
@section('content')
<div class="row-fluid">
	@if(count($errors)>0)
	<ul>
		
		<div class="note note-success"> @foreach($errors->all() as $error)
			<strong style="color: red"> {{  $error }}</strong><br>
			@endforeach
		</div>
		
	</ul>
	@endif
	<div class="span12">
		
		<div class="widget-box">
			<div class="widget-header">
				<h4>Edit Newsletter</h4>
				<span class="widget-toolbar">
				</span>	</div>
				<div class="widget-body"><div class="widget-body-inner">
					<div class="widget-main">
					{{ Form::open(array('method'=>'PUT','route' => ['newsletters.update', $newsletters->id],'files' =>true,'enctype'=>'multipart/form-data')) }}

							<div class="row-fluid">
								  <input type="hidden" name="noimg" value="No-Image" placeholder="">
								<input type="hidden" name="_token" value="{{csrf_token()}}">
								<label for="form-field-8">News Title</label>
								<input name="title" value="{{$newsletters->title}}" class="span6 limited" type="text" id="form-field-4" placeholder="Enter Newsletters">
							</div>
							<hr>
							<div class="row-fluid">
								<label for="form-field-9">Project Name</label>
								<select  name="project_id" class="span6" id="form-field-select-1">
									
									<option selected value="{{$newsletters->project->id}}">{{$newsletters->project->project_name}}</option>
									@foreach($projects as $project)
									<option value="{{$project->id}}">{{$project->project_name}}</option>
									@endforeach
								</select>
							</div>
							<div class="row-fluid">
								
								<label for="form-field-8">Link</label>
								<input name="link" value="{{$newsletters->link}}" class="span6 limited" type="text" id="form-field-4" placeholder="Enter Link">
							</div>
							<hr>
							<div class="row-fluid">
								<label for="form-field-9">Status</label>
								<select  name="status" class="span6" id="form-field-select-1">
									
									<option selected value="{{$newsletters->status}}">
									@if($newsletters->status==1)
						{{'Enabled'}}@else{{'Disabled'}}@endif	</option>
									<option value="1">Enabled</option>
									<option value="0">Disabled</option>
								</select>
							</div>
							<div class="row-fluid">
								<label for="form-field-8">Newsletter Pdf File</label>
								<img src="{{url('/images/newsletters/'.$newsletters->file)}}" width="100px"  alt="No Image"><br>
								<input type="file" name="image" value="" placeholder="">
							</div><hr>
						<div class="row-fluid">
								<label for="form-field-8">Newsletters</label>
								<img src="{{url('/images/newsletters/'.$newsletters->thumbnail)}}" width="300px"  alt="No Image"><br>
								<input type="file" name="thumbnail" value="" placeholder="">
							</div>
						
							<div class="form-actions">
								<button class="btn btn-info" type="submit"><i class="icon-ok"></i> Submit</button>
								&nbsp; &nbsp; &nbsp;
								<button class="btn" type="reset"><i class="icon-undo"></i> Reset</button>
							</div> </form>
						</div>
					</div></div>
				</div>
			</div>
			
		</div>
		@endsection

resources/views/brouchers/index.blade.php
@extends('layouts.app')
@section('title','Newsletter List')
@section('content')<button class="btn-link" style="float: right">  <a href="{{url('newsletters/create')}}">Create Newsletters</a></button><br><br>
<div class="row-fluid">
	<!-- <h3 class="header smaller lighter blue">jQuery dataTables</h3> -->
	
	<div class="table-header">
		Newsletters List
	</div>
	@if(session('message'))
	<div class="note note-success"><p>{{session('message')}}</p> </div>
	@endif
	<div id="table_report_wrapper" class="dataTables_wrapper" role="grid"><div class="row-fluid"><div class="span6"><div id="table_report_length" class="dataTables_length"><label>Display <select size="1" name="table_report_length" aria-controls="table_report"><option value="10" selected="selected">10</option><option value="25">25</option><option value="50">50</option><option value="100">100</option></select> records</label></div></div><div class="span6"><div class="dataTables_filter" id="table_report_filter"><form method="get" action="{{url('/newsletters/search')}}">
	{!! Form::text("title",isset($title)?$Newsletters->title:null,[
	"class"=>"form-control input-inline input-large".($errors->has('title')?" is-invalid":"")
	,"autofocus"
	,"placeholder"=>"Enter Title"
	,"required"]) !!}
	<select  name="project_id" class="span6" id="form-field-select-1">
		
		@foreach($projects as $project)
		<option value="{{$project->id}}">{{$project->project_name}}</option>
		@endforeach
	</select>
	{{ Form::button('<i class="fa fa-search"></i> &nbsp;Search</button>', ['type' => 'submit', 'class' =>'btn btn-small btn-primary'] )  }}
</form></div></div></div><table id="table_report" class="table table-striped table-bordered table-hover dataTable" aria-describedby="table_report_info">
<thead>
	<tr role="row"><th class="center sorting_disabled" role="columnheader" rowspan="1" colspan="1" aria-label="
		
		" style="width: 71px;">
		<label><input type="checkbox"><span class="lbl"></span></label>
		</th><th class="sorting" role="columnheader" tabindex="0" aria-controls="table_report" rowspan="1" colspan="1" aria-label="Domain: activate to sort column ascending" style="width: 207px;">Title</th><th class="sorting" role="columnheader" tabindex="0" aria-controls="table_report" rowspan="1" colspan="1" aria-label="Price: activate to sort column ascending" style="width: 140px;">Project Name</th><th class="hidden-480 sorting" role="columnheader" tabindex="0" aria-controls="table_report" rowspan="1" colspan="1" aria-label="Clicks: activate to sort column ascending" style="width: 151px;">Status</th><th class="hidden-480 sorting" role="columnheader" tabindex="0" aria-controls="table_report" rowspan="1" colspan="1" aria-label="Status: activate to sort column ascending" style="width: 202px;">Sort Order</th><th class="sorting" role="columnheader" tabindex="0" aria-controls="table_report" rowspan="1" colspan="1" aria-label="Domain: activate to sort column ascending" style="width: 207px;">Thumbnail</th>
		<th class="sorting_disabled" role="columnheader" rowspan="1" colspan="1" aria-label="" style="width: 50px;">Actions</th></tr>
	</thead>
	
	
	<tbody role="alert" aria-live="polite" aria-relevant="all">
		@php $count=0;
		@endphp
		@foreach($newsletters as $newsletters)
		@php $count++;
		@endphp
		<tr class="odd">
			<td class="center  sorting_1">
				<label><input type="checkbox"><span class="lbl"></span></label>
			</td>
			<td class=" "><a href="#">{{$newsletters->title}}</a></td>
			<td class=" ">
				
			{{$newsletters->project->project_name}}</td>
			<td class="">@if($newsletters->status==1)
				{{'Enabled'}}@else{{'Disabled'}}@endif
			</td>
			<td class="">{{$newsletters->sort_order}}</td>
			<td class="">
				
			<img src="{{url('/images/newsletters/'.$newsletters->thumbnail)}}" width="100px"  alt="No Image"></td>
			<td class=" ">
				<div class="hidden-phone visible-desktop btn-group">
					<a href="{{ route('newsletters.show', $newsletters->id) }}">
					<button class="btn btn-mini btn-success"><i class="icon-search"></i></button> </a>
					<a href="{{ route('newsletters.edit', $newsletters->id) }}">
					<button class="btn btn-mini btn-info"><i class="icon-edit"></i></button></a>
					{!! Form::open(['class'=>'confirm_delete_form inline','method' => 'DELETE','route' => ['newsletters.destroy', $newsletters->id ] ,'data-partial'=>'/newsletters']) !!}	<button class="btn btn-mini btn-danger"><i class="icon-trash"></i></button> {!! Form::close() !!}
					<!-- <button class="btn btn-mini btn-warning"><i class="icon-flag"></i></button> -->
				</div>
				<div class="hidden-desktop visible-phone">
					<div class="inline position-relative">
						<button class="btn btn-minier btn-yellow dropdown-toggle" data-toggle="dropdown"><i class="icon-caret-down icon-only"></i></button>
						<ul class="dropdown-menu dropdown-icon-only dropdown-yellow pull-right dropdown-caret dropdown-close">
							<li><a href="#" class="tooltip-success" data-rel="tooltip" title="" data-placement="left" data-original-title="Edit"><span class="green"><i class="icon-edit"></i></span></a></li>
							<li><a href="#" class="tooltip-warning" data-rel="tooltip" title="" data-placement="left" data-original-title="Flag"><span class="blue"><i class="icon-flag"></i></span> </a></li>
							<li><a href="#" class="tooltip-error" data-rel="tooltip" title="" data-placement="left" data-original-title="Delete"><span class="red"><i class="icon-trash"></i></span> </a></li>
						</ul>
					</div>
				</div>
			</td>
		</tr>  @endforeach
		</tbody></table><div class="row-fluid"><div class="span6"><div class="dataTables_info" id="table_report_info">Showing 1 to 10 of 22 entries</div></div><div class="span6"><div class="dataTables_paginate paging_bootstrap pagination"><ul><li class="prev disabled"><a href="#"><i class="icon-double-angle-left"></i></a></li><li class="active"><a href="#">1</a></li><li><a href="#">2</a></li><li><a href="#">3</a></li><li class="next"><a href="#"><i class="icon-double-angle-right"></i></a></li></ul></div></div></div></div>
		
	</div>
	@endsection